### ISSUE TITLE
CSS Missing

### ISSUE THREAD

**Issue by mohit-design** [Aqro/Physics-menu-threejs-cannonjs#1]
I can't find out the css. Can you please provide?

**Comment by MedleyMedia** [comment]
This looks very cool! Excited to play with it but am having troubles installing. Have uploaded all the files through cPanel and in Terminal execute "npm install" but just get "bash: npm: command not found". Is there something missing from the package? In the HTML there's src="dist/app.js" which isn't included in the package.

**Comment by Aqro** [comment]
Indeed, you need to have [node](https://nodejs.org/en/) installed on your computer (or server) to compile the code and use it.
